const { chromium } = require('D:/naturales_1/node_modules/playwright');
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: 'C:/Users/javie/AppData/Local/ms-playwright/chromium-1228/chrome-win64/chrome.exe' });
  const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
  await ctx.clearCookies();
  const page = await ctx.newPage();
  await page.route('**/*', (route) => { const h = Object.assign({}, route.request().headers(), { 'Cache-Control': 'no-cache, no-store', 'Pragma': 'no-cache' }); route.continue({ headers: h }); });
  await page.goto('http://localhost:8080/unidades/biologia/celulas/index.html?cb=' + Date.now(), { waitUntil: 'networkidle' });
  await page.evaluate(() => { document.querySelectorAll('img[loading=lazy]').forEach((i) => { i.loading = 'eager'; }); });
  await page.evaluate(() => Promise.all(Array.from(document.images).map((img) => { if (img.complete) return Promise.resolve(); return new Promise((r) => { img.addEventListener('load', r, { once: true }); img.addEventListener('error', r, { once: true }); setTimeout(r, 5000); }); })));
  await page.waitForTimeout(800);
  const card = page.locator('a[href="animal.html"]').first();
  const box = await card.boundingBox();
  await card.scrollIntoViewIfNeeded();
  await page.waitForTimeout(300);
  await card.screenshot({ path: 'D:/naturales_1/output/inspect/cards/v3_animal_NOCACHE.png' });
  const info = await page.evaluate(() => Array.from(document.querySelectorAll('a[href="animal.html"] img')).map((i) => ({ src: i.src, nw: i.naturalWidth, nh: i.naturalHeight, currentSrc: i.currentSrc })));
  console.log(JSON.stringify(info, null, 2));
  await browser.close();
})();
